from typing import Protocol, Any

class ValidationServiceInterface(Protocol):
    def get_error_message(self, message_key, **kwargs) -> Any: ...
    def create_guard_function(self, validation_logic, error_message) -> Any: ...
